# Site settings
title: Atef Hares
url: "https://atefhares.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/blog" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
description: >
  Atef Hares - Self learner and Software developer

show_dir_listing: false
version: v1.0.0

# Outputting
permalink: /:title/
paginate_path: "page:num"
paginate: 5
timezone: Africa/Cairo

quiet:    false
verbose:  false
defaults: []

liquid:
  error_mode: warn

# Your information
email: atef_moh@sci.asu.edu.eg
author: Atef Hares
avatar: "https://atefhares.github.io/assets/images/profile.png"
profile: Self learner and Software developer
#twitter_username: mratefhares
github_username:  atefhares
stack-overflow_username:  atef-hares
linkedin_username:  atefhares

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Plugins
whitelist: []
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["Gemfile", "Gemfile.lock", "LICENSE.md", "README.md", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false


# Build settings
highlighter: rouge
markdown: kramdown

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
